server.port:
  @eureka.server.port@
# eureka
spring:
  application.name: @application.name@
  profiles.active: @profiles.active@
eureka.client:
  register-with-eureka: false
  fetch-registry: false

logging.level.com.netflix:
  eureka: OFF
  discovery: OFF

management:
  port: 54001  // 指定监听端口，不指定则语server端口一直
  health:
    db:
      enabled: true
    mail:
      enabled: true
  security:
    enabled: false // 指定访问信息不进行用户验证

endpoints.info.enabled: truee

