server:
  port: @service.client.b.port@
  #servlet:
   # context-path: /product
spring:
  application:
    name: micro-service-b

################ Eureka ################
eureka:
  client:
    service-url:
      defaultZone: @eureka.client.service-url.defaultZone@