server:
  port: 8080
  #servlet:
   # context-path: /product
spring:
  application:
    name: eureka-client-demo

################ Eureka ################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka