################ 项目基本配置 ################
server:
  port: 8080
  #servlet:
   # 项目访问路径前缀
   # context-path: /product
spring:
  application:
  # 注册到Eureka的服务名
    name: eureka-client-demo

################ Eureka配置 ################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka