server:
  port: @service.client.a.port@
  #servlet:
   # context-path: /product
spring:
  application:
    name: micro-service-a

################ Eureka ################
eureka:
  client:
    service-url:
      defaultZone: @eureka.client.service-url.defaultZone@

ribbon:
  eureka:
    enabled: true

microservice-provider-user:
  ribbon:
    listOfServers: localhost:7901,localhost:7902
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule